In [1]:
import numpy as np
import pandas as pd

In [2]:
# deleted kmpl, CC, bhp , in microfodt excel
# and 
# converted fuel,seller_type,transmission,owner to numerical values
# CNG=10,   LPG=20,     Deisel=30,      Petrol=40
# Dealer=10,     Individual=20,     trustmark dealer=30
# automatic = 10,      Manual= 20
# testdrive=10    ,1owner=20,     2owner=30,      3owner=40,  4ownerandmore=50

In [3]:
data = pd.read_csv("car_price_edited.csv")
print(data)

                              name  year  selling_price  km_driven  fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500    30   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000    30   
2         Honda City 2017-2020 EXi  2006         158000     140000    40   
3            Hyundai i20 Sportz 30  2010         225000     127000    30   
4           Maruti Swift VXI BSIII  2007         130000     120000    40   
...                            ...   ...            ...        ...   ...   
8123             Hyundai i20 Magna  2013         320000     110000    40   
8124         Hyundai Verna CRDi SX  2007         135000     119000    30   
8125        Maruti Swift Dzire ZDi  2009         382000     120000    30   
8126               Tata Indigo CR4  2013         290000      25000    30   
8127               Tata Indigo CR4  2013         290000      25000    30   

      seller_type  transmission  owner  mileage  engine  max_power  \
0              20

In [4]:
data = pd.read_csv("car_price_edited.csv")
# deleted name column
data = data.drop(['name'],axis=1)
# deleted torque colimn cause rn i dont know how to deal with that
data = data.drop(['torque'],axis=1)
# drop all rows/training examples with some null values rn i dont know how to deal with that
data = data.dropna(axis=0)
#store selling price in datay and drop it from data
datay = data['selling_price']
data = data.drop(['selling_price'],axis =1)
print(data)
print(datay)

      year  km_driven  fuel  seller_type  transmission  owner  mileage  \
0     2014     145500    30           20            20     20    23.40   
1     2014     120000    30           20            20     30    21.14   
2     2006     140000    40           20            20     40    17.70   
3     2010     127000    30           20            20     20    23.00   
4     2007     120000    40           20            20     20    16.10   
...    ...        ...   ...          ...           ...    ...      ...   
8123  2013     110000    40           20            20     20    18.50   
8124  2007     119000    30           20            20     50    16.80   
8125  2009     120000    30           20            20     20    19.30   
8126  2013      25000    30           20            20     20    23.57   
8127  2013      25000    30           20            20     20    23.57   

      engine  max_power  seats  
0     1248.0      74.00    5.0  
1     1498.0     103.52    5.0  
2     1497.0

In [5]:
#converting to numpy array
x = data.to_numpy()
y = datay.to_numpy()
x0= np.ones((x.shape[0],1))
x = np.hstack((x0,x))
print(x)
print(y)

[[1.0000e+00 2.0140e+03 1.4550e+05 ... 1.2480e+03 7.4000e+01 5.0000e+00]
 [1.0000e+00 2.0140e+03 1.2000e+05 ... 1.4980e+03 1.0352e+02 5.0000e+00]
 [1.0000e+00 2.0060e+03 1.4000e+05 ... 1.4970e+03 7.8000e+01 5.0000e+00]
 ...
 [1.0000e+00 2.0090e+03 1.2000e+05 ... 1.2480e+03 7.3900e+01 5.0000e+00]
 [1.0000e+00 2.0130e+03 2.5000e+04 ... 1.3960e+03 7.0000e+01 5.0000e+00]
 [1.0000e+00 2.0130e+03 2.5000e+04 ... 1.3960e+03 7.0000e+01 5.0000e+00]]
[450000 370000 158000 ... 382000 290000 290000]


In [6]:
# m is no of training examples (from 1 to m)
m = x.shape[0]
# n is no of inputs/features including x0
n = x.shape[1]
# para is vector of size n initialized to ones
para = np.ones((n))

In [ ]:
# these are the failed attemps : 
'''
alpha = pow(10,-1)
iterations = 1
print(m)
print(n)
for hello in range(iterations):
    JK = np.ones((n))
    for j in range(n):
        summ=0
        for i in range(m):
            summ = summ + np.sum(x[i]*para)*x[i][j]
        JK[j] = summ
    para = para - alpha * JK
    alpha = alpha * 0.001
    print(hello)
print(para)

def hypo(i):
    return np.sum(para*x[i])
alpha = pow(10,-5)
consterm = alpha / m
step = 0
epochs = 100
print("iterarions:", end = " ")
print(epochs)
print("alpha:", end = " ")
print(alpha)

for k in range(epochs):
    for j in range(0,n):
        for i in range(0,m):
            step = step + ((hypo(i)-y[i])*(x[i][j]))
        para[j] =para[j] - consterm*step
        step = 0
    consterm = consterm * 0.1
    print(k , end = " ")

print(" ")
print(para)
# Values were blowing up.. 
# This was para after three iteratinons !
# [-2.26913336e+27 -4.56691697e+30 -2.62684188e+32 -7.52267778e+28
# -4.37734333e+28 -4.36606272e+28 -5.92357781e+28 -4.27664913e+28
# -3.50330747e+30 -2.05291208e+29 -1.26962968e+28]
# it was suppossed to be heading towards 
# [-6.67499421e+07  3.35967141e+04 -1.06389502e+00 -4.51495153e+03
# -2.19126792e+04 -4.77882723e+04 -1.88765379e+03  1.16746207e+04
#  9.34935143e+01  1.26804145e+04 -3.81241777e+04]
# reducing alpha wasnt working....

'''

In [8]:
# normalizing features
for i in range(1,n):
    avg = np.sum(x[:,i])/m
    ranger = max(x[:,i])- min(x[:,i])
    for j in range(m):
      x[j,i] = (x[j,i]-avg)/ranger
print(x)

[[ 1.00000000e+00  6.17836502e-04  3.23290670e-02 ... -7.07076607e-02
  -4.78958974e-02 -3.46993844e-02]
 [ 1.00000000e+00  6.17836502e-04  2.15260696e-02 ...  1.31849568e-02
   3.24962595e-02 -3.46993844e-02]
 [ 1.00000000e+00 -3.07074471e-01  2.99990088e-02 ...  1.28493863e-02
  -3.70026512e-02 -3.46993844e-02]
 ...
 [ 1.00000000e+00 -1.91689856e-01  2.15260696e-02 ... -7.07076607e-02
  -4.81682285e-02 -3.46993844e-02]
 [ 1.00000000e+00 -3.78437020e-02 -1.87203912e-02 ... -2.10432311e-02
  -5.87891436e-02 -3.46993844e-02]
 [ 1.00000000e+00 -3.78437020e-02 -1.87203912e-02 ... -2.10432311e-02
  -5.87891436e-02 -3.46993844e-02]]


In [9]:
#using direct formula
parameters = np.dot(np.dot(np.linalg.inv(np.dot(np.transpose(x),x)),np.transpose(x)),y)
print(parameters)

[  649813.72084492   873514.56562901 -2511277.39431106  -135448.54597312
  -438253.58438609  -477882.72288427   -75506.15149682   490334.06998172
   278610.67266111  4656248.20140303  -457490.13243072]


In [10]:
#using gradient descent / stochastic 
iterations = 100000
alpha = pow(10,-4)

In [11]:
for i in range(iterations):
    hypo = np.dot(x,para)
    para = para - alpha * np.dot(np.transpose(x),(hypo - y))
    # mse = np.sum(np.square(hypo-y))/(2*m)

In [12]:
#prints error
print(para-parameters)

[-1.16415322e-10  3.72529030e-08  8.37258995e-07  1.80443749e-08
  3.84170562e-09  8.49831849e-09 -8.10541678e-09 -8.32369551e-09
 -1.06345396e-07  2.00234354e-07  3.73111106e-08]


In [13]:
# wait, for predicting, first take input from user ( UI PART I HATE TO TYPE OUT )
#Convert the strings into given codes from this

        # CNG=10,   LPG=20,     Deisel=30,      Petrol=40
        # Dealer=10,     Individual=20,     trustmark dealer=30
        # automatic = 10,      Manual= 20
        # testdrive=10    ,1owner=20,     2owner=30,      3owner=40,  4ownerandmore=50
# Normalize input data like before
# Feed it into hypothesis function , (which multiplies it with para matrix(which we already have calculate in this Source.py))
# the output is the predicted price
